"""
Lenny Growth Assistant — Agent Runtime Models & Contracts

Defines validated Pydantic models for agent skill requests, streaming event
structures, and execution outputs matching Section 10 of docs/implementation-contract.md.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, Field

from app.retrieval.models import Citation, EvidenceChunk


class AgentSkill(str, Enum):
    """Supported specialized agent skills."""
    GROUNDED_QA = "grounded_qa"
    SHIP30_WRITER = "ship30_writer"
    ARTIFACT_GENERATOR = "artifact_generator"


class AgentRequestPayload(BaseModel):
    """Payload sent to the Pi agent runtime."""
    skill: AgentSkill = Field(..., description="Target skill to execute")
    query: str = Field(..., description="User query or instruction")
    evidence: List[EvidenceChunk] = Field(default_factory=list, description="Retrieved transcript evidence chunks")
    conversation_history: Optional[List[Dict[str, str]]] = Field(
        default=None, description="Prior conversation turns (role, content)"
    )
    provider: str = Field(default="openai", description="Model provider ('openai' or 'ollama')")
    model: Optional[str] = Field(default=None, description="Optional model identifier override")
    mock_mode: bool = Field(default=False, description="Whether to execute in deterministic offline mock mode")

    def to_node_payload(self) -> Dict[str, Any]:
        """Serializes payload into a JSON-compatible dict for the Node.js Pi runtime."""
        return {
            "skill": self.skill.value,
            "query": self.query,
            "evidence": [
                {
                    "chunk_id": str(c.chunk_id),
                    "episode_title": c.episode_title,
                    "guest_name": c.guest_name,
                    "content": c.content,
                    "timestamp": c.timestamp,
                    "source_url": c.source_url,
                    "similarity": c.similarity,
                }
                for c in self.evidence
            ],
            "conversation_history": self.conversation_history or [],
            "provider": self.provider,
            "model": self.model,
            "mock_mode": self.mock_mode,
        }


class StreamEventModel(BaseModel):
    """Represents a single normalized Server-Sent Event (SSE) emitted by the agent runtime."""
    event: str = Field(..., description="Event type: status, token, citation, artifact, done, or error")
    data: Dict[str, Any] = Field(..., description="Structured event payload")


class AgentExecutionResult(BaseModel):
    """Final assembled outcome of an agent skill execution."""
    content: str = Field(..., description="Full text generated by the agent")
    citations: List[Citation] = Field(default_factory=list, description="Associated source citations")
    artifact: Optional[Dict[str, Any]] = Field(default=None, description="Generated artifact payload if produced")
    provider: str = Field(..., description="Provider that generated the response")
    model: str = Field(..., description="Model that generated the response")
    tokens_prompt: int = Field(default=0, description="Input tokens used")
    tokens_completion: int = Field(default=0, description="Output tokens used")
    cost_usd: float = Field(default=0.0, description="Calculated expenditure in USD")
